###
POST http://localhost:8080/users
Content-Type: application/json

{
  "user": {
    "email": "email@email.com",
    "password": "password"
  }
}

###
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "user": {
    "email": "email@email.com",
    "password": "password"
  }
}

###
GET http://localhost:8080/user
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cGUiOiJKV1QifQ.eyJzdWIiOjEsIm5hbWUiOiJlbWFpbEBlbWFpbC5jb20iLCJpYXQiOjE2NjkwNDgxMjR9.X_Fcri8XDhw1BBaPG4zzVwYGY4Ki-LUiYBxxZjOrMZc